--1. Data Exploration

---1.1 Explore All Objects in The Database
SELECT *
FROM INFORMATION_SCHEMA.TABLES

--Output: 

---DataWarehouseAnalytics	gold	dim_customers	BASE TABLE
---DataWarehouseAnalytics	gold	dim_products	BASE TABLE
---DataWarehouseAnalytics	gold	fact_sales	    BASE TABLE



---1.2 Explore All Columns in The Database
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'



---1.3 Explore All Countries Our Customers Came From
SELECT DISTINCT country
FROM gold.dim_customers
WHERE country IS NOT NULL

--Output: 

---Germany
---United States
---Australia
---United Kingdom
---Canada
---France


---1.4 Explore All Categories , Subcategories "The Major Divisions"
SELECT DISTINCT category 
FROM gold.dim_products
WHERE category IS NOT NULL

--Output:

---Accessories
---Bikes
---Clothing
---Components


---1.5 Find the Date of The First and Last Order
SELECT MIN(order_date) AS "First Order Date" , MAX(order_date) AS "Last Order Date"
FROM gold.fact_sales

--Output: 

---2010-12-29	2014-01-28


---1.7 How Many Years of Sales Are Available
SELECT DATEDIFF(YEAR , MIN(order_date) , MAX(order_date)) AS  "Order Range Years"
FROM gold.fact_sales

--Output:
---4


---1.8 Find The Youngest and The Oldest Customer
SELECT MIN(birthdate) AS "Oldest Birthdate",
       MAX(birthdate) AS "Youngest Birthdate"
FROM gold.dim_customers

--Output: 

---1916-02-10	1986-06-25


---1.9 How Many Years of Oldest Customer
SELECT DATEDIFF(YEAR , MIN(birthdate) , GETDATE()) AS "Oldest Age",
       DATEDIFF(YEAR , MAX(birthdate) , GETDATE()) AS "Youngest Age"
FROM gold.dim_customers

--Output:

---109	39


--2. Measures

---2.1 Find The Total Sales.
SELECT SUM(price) AS "Total Sales"
FROM gold.fact_sales

--Output: 29355710


---2.2 Find How Many Items Sold.
SELECT SUM(quantity) AS "Total Quantity"
FROM gold.fact_sales

--Output: 60423


---2.3 Find The Average Selling Price.
SELECT AVG(price) AS "Average Price"
FROM gold.fact_sales

--Output: 486


---2.4 Find The Total Number of Orders.
SELECT COUNT(DISTINCT order_number) AS "Total Orders"
FROM gold.fact_sales

--Output: 27659


---2.5 Find The Total Number of Products.
SELECT COUNT(DISTINCT product_id) AS "Total Products"
FROM gold.dim_products

--Output: 295


---2.6 Find The Total Number of Customers.
SELECT COUNT(DISTINCT customer_key) AS "Total Customers"
FROM gold.fact_sales

--Output: 18484


--2.7 Generate a Report That Shows all Key Matrics of The Business
SELECT 'Total Sales' AS "Measure Name" , SUM(sales_amount) AS "Measure Value"
FROM gold.fact_sales

UNION ALL

SELECT 'Total Quantity' , SUM(quantity) 
FROM gold.fact_sales

UNION ALL 

SELECT 'Average Price' , AVG(price)
FROM gold.fact_sales

UNION ALL

SELECT 'Total Orders' , COUNT(DISTINCT order_number) 
FROM gold.fact_sales

UNION ALL


SELECT 'Total Products' , COUNT(DISTINCT product_id) 
FROM gold.dim_products

UNION ALL

SELECT 'Total Customer' , COUNT(DISTINCT customer_key) 
FROM gold.fact_sales


--3. Measures and Dimensions

---3.1 Find The Total Customers By Countries
SELECT country , COUNT(customer_id) AS "Total Customers"
FROM gold.dim_customers
WHERE country != 'n/a'
GROUP BY country
ORDER BY "Total Customers" DESC

--Output:

---United States	7482
---Australia	    3591
---United Kingdom	1913
---France	        1810
---Germany	        1780
---Canada	        1571


---3.2 Find The Total Customers by Gender
SELECT gender , COUNT(customer_id) AS "Total Customers"
FROM gold.dim_customers
WHERE gender != 'n/a'
GROUP BY gender
ORDER BY  "Total Customers" DESC

--Output:

---Male	    9341
---Female	9128


--3.3 Find The Total Products by Each Category.
SELECT category , COUNT(product_id) AS "Total Products"
FROM gold.dim_products
WHERE category != 'n/a'
GROUP BY category
ORDER BY "Total Products" DESC

--Output:

---Components	127
---Bikes	     97
---Clothing	     35
---Accessories	 29


---3.4 What is The Average Costs in Each Category?
SELECT category , AVG(cost) AS "Average Cost"
FROM gold.dim_products
WHERE category != 'n/a'
GROUP BY category
ORDER BY "Average Cost" DESC

--Output:

---Bikes	    949
---Components	264
---Clothing	     24
---Accessories	 13


---3.5 What is The Total Revenue Generated For Each Category?
SELECT DP.category , SUM(FS.sales_amount) AS "Total Revenue"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_products AS DP
ON DP.product_key = FS.product_key
WHERE DP.category != 'n/a'
GROUP BY  DP.category
ORDER BY "Total Revenue" DESC

--Output:

---Bikes	    28316272
---Accessories	  700262
---Clothing	      339716


---3.6 Find The Total Revenue That is Generated By Each Customer?
select DC.customer_id , 
       DC.customer_key , 
       DC.first_name + ' ' + DC.last_name AS "Customer Name" , 
       SUM(FS.sales_amount) AS "Total Revenue"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_customers AS DC
ON DC.customer_key = FS.customer_key
GROUP BY  DC.customer_id ,  DC.customer_key , DC.first_name + ' ' + DC.last_name
ORDER BY "Total Revenue" DESC , customer_id ASC

--Output: 

--The First
---12132 1133  Kaitlyn Henderson   13294

--The Last
---28968  17969  Marcus Morgan	2


---3.7 What is The Distribution of Sold Items Across Countries?

SELECT DC.country , SUM(FS.quantity) AS "Total Items Sold" 
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_customers AS DC
ON DC.customer_key = FS.customer_key
GROUP BY DC.country
ORDER BY "Total Items Sold" DESC

--Output:

---United States	20481
---Australia	    13346
---Canada	         7630
---United Kingdom	 6910
---Germany	         5626
---France	         5559


--4. Ranking

---4.1 Which 5 Products That Generates The Highest Revenue?
SELECT TOP (5) DP.product_name , SUM(FS.sales_amount) AS "Total Revenue"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_products AS DP
ON DP.product_key = FS.product_key
GROUP BY DP.product_name 
ORDER BY "Total Revenue" DESC

--Output:

---Mountain-200 Black- 46	1373454
---Mountain-200 Black- 42	1363128
---Mountain-200 Silver- 38	1339394
---Mountain-200 Silver- 46	1301029
---Mountain-200 Black- 38	1294854


SELECT * 
FROM (SELECT DP.product_name , 
       SUM(FS.sales_amount) AS "Total Revenue",
       RANK() OVER (ORDER BY SUM(FS.sales_amount) DESC) AS "Rank"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_products AS DP
ON DP.product_key = FS.product_key
GROUP BY DP.product_name ) AS Sub_Query
WHERE "Rank" <= 5

--Output:

---Mountain-200 Black- 46	1373454	1
---Mountain-200 Black- 42	1363128	2
---Mountain-200 Silver- 38	1339394	3
---Mountain-200 Silver- 46	1301029	4
---Mountain-200 Black- 38	1294854	5


---4.2 What are The Worst-Performing Products in Terms of Sales?
SELECT TOP(5) DP.product_name , SUM(FS.sales_amount) AS "Total Revenue"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_products AS DP
ON DP.product_key = FS.product_key
GROUP BY  DP.product_name
ORDER BY "Total Revenue" ASC

--Output:

---Racing Socks- L	       2430
---Racing Socks- M	       2682
---Patch Kit/8 Patches	   6382
---Bike Wash - Dissolver   7272
---Touring Tire Tube	   7440



SELECT * 
FROM (SELECT DP.product_name , 
       SUM(FS.sales_amount) AS "Total Revenue",
       RANK() OVER (ORDER BY SUM(FS.sales_amount) ASC) AS "Rank"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_products AS DP
ON DP.product_key = FS.product_key
GROUP BY DP.product_name ) AS Sub_Query
WHERE "Rank" <= 5

--Output:

---Racing Socks- L	       2430  1
---Racing Socks- M	       2682  2
---Patch Kit/8 Patches	   6382  3
---Bike Wash - Dissolver   7272  4
---Touring Tire Tube	   7440  5


---4.3 Which 5 Subcategories That Generates The Highest Revenue?
SELECT TOP (5) DP.subcategory , SUM(FS.sales_amount) AS "Total Revenue"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_products AS DP
ON DP.product_key = FS.product_key
GROUP BY DP.subcategory
ORDER BY "Total Revenue" DESC

--Output:

---Road Bikes	   14519438
---Mountain Bikes	9952254
---Touring Bikes	3844580
---Tires and Tubes	 244634
---Helmets	         225435

SELECT * 
FROM (SELECT DP.subcategory , 
       SUM(FS.sales_amount) AS "Total Revenue",
       RANK() OVER (ORDER BY SUM(FS.sales_amount) DESC) AS "Rank"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_products AS DP
ON DP.product_key = FS.product_key
GROUP BY DP.subcategory ) AS Sub_Query
WHERE "Rank" <= 5


--Output:

---Road Bikes	   14519438   1
---Mountain Bikes	9952254   2
---Touring Bikes	3844580   3
---Tires and Tubes	 244634   4
---Helmets	         225435   5


---4.4 What are The Worst-Performing Subcategories in Terms of Sales?
SELECT TOP(5) DP.subcategory , SUM(FS.sales_amount) AS "Total Revenue"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_products AS DP
ON DP.product_key = FS.product_key
GROUP BY  DP.subcategory
ORDER BY "Total Revenue" ASC

--Output:

---Socks	 5112
---Cleaners	 7272
---Caps	    19710
---Gloves	34320
---Vests	36160




SELECT * 
FROM (SELECT DP.subcategory , 
       SUM(FS.sales_amount) AS "Total Revenue",
       RANK() OVER (ORDER BY SUM(FS.sales_amount) ASC) AS "Rank"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_products AS DP
ON DP.product_key = FS.product_key
GROUP BY DP.subcategory ) AS Sub_Query
WHERE "Rank" <= 5


--Output:

---Socks	 5112   1
---Cleaners	 7272   2
---Caps	    19710   3
---Gloves	34320   4
---Vests	36160   5



--4.5 Find The Top 10 Customers Who Have Generated The Highest Revenue.
SELECT TOP (10) DC.customer_key , 
           DC.customer_id , 
           DC.first_name + ' ' + DC.last_name AS "Customer Name",
           SUM(FS.sales_amount) AS "Total Revenue"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_customers AS DC
ON DC.customer_key = FS.customer_key
GROUP BY DC.customer_key , DC.customer_id , DC.first_name + ' ' + DC.last_name
ORDER BY "Total Revenue" DESC

--Output:
---1133	  12132	  Kaitlyn Henderson	13294 
---1302	  12301	  Nichole Nara	    13294 
---1309	  12308	  Margaret He	    13268 
---1132	  12131	  Randall Dominguez	13265 
---1301	  12300	  Adriana Gonzalez	13242 
---1322	  12321	  Rosa Hu	        13215 
---1125	  12124	  Brandi Gill	    13195 
---1308	  12307	  Brad She	        13172 
---1297	  12296	  Francisco Sara	13164 
---434	  11433	  Maurice Shan	    12914 

SELECT *
FROM(SELECT DC.customer_key,
            DC.customer_id , 
            DC.first_name + ' ' + DC.last_name AS "Customer Name",
            SUM(FS.sales_amount) AS "Total Revenue",
            ROW_NUMBER() OVER(ORDER BY SUM(FS.sales_amount) DESC) AS Ranking
      FROM gold.fact_sales AS FS
      INNER JOIN gold.dim_customers AS DC
      ON DC.customer_key = FS.customer_key
      GROUP BY DC.customer_key , DC.customer_id , DC.first_name + ' ' + DC.last_name) AS Sub_Query
WHERE Ranking <= 10


--Output:

---1133	  12132	  Kaitlyn Henderson	13294  1
---1302	  12301	  Nichole Nara	    13294  2
---1309	  12308	  Margaret He	    13268  3
---1132	  12131	  Randall Dominguez	13265  4
---1301	  12300	  Adriana Gonzalez	13242  5
---1322	  12321	  Rosa Hu	        13215  6
---1125	  12124	  Brandi Gill	    13195  7
---1308	  12307	  Brad She	        13172  8
---1297	  12296	  Francisco Sara	13164  9
---434	  11433	  Maurice Shan	    12914  10


--4.6 Find The Top 3 Customers Who Have Generated The Lowest Revenue.
SELECT TOP (3) DC.customer_key , 
           DC.customer_id , 
           DC.first_name + ' ' + DC.last_name AS "Customer Name",
           SUM(FS.sales_amount) AS "Total Revenue"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_customers AS DC
ON DC.customer_key = FS.customer_key
GROUP BY DC.customer_key , DC.customer_id , DC.first_name + ' ' + DC.last_name
ORDER BY "Total Revenue" ASC

--Output:

---17017	28016	Cody Sanders	   2
---17777	28776	Abigail Morris	   2
---17095	28094	Melanie Peterson   2


SELECT *
FROM(SELECT DC.customer_key,
            DC.customer_id , 
            DC.first_name + ' ' + DC.last_name AS "Customer Name",
            SUM(FS.sales_amount) AS "Total Revenue",
            ROW_NUMBER() OVER(ORDER BY SUM(FS.sales_amount) ASC) AS Ranking
      FROM gold.fact_sales AS FS
      INNER JOIN gold.dim_customers AS DC
      ON DC.customer_key = FS.customer_key
      GROUP BY DC.customer_key , DC.customer_id , DC.first_name + ' ' + DC.last_name) AS Sub_Query
WHERE Ranking <= 3


--Output:

---17017	28016	Cody Sanders	   2   1
---17777	28776	Abigail Morris	   2   2
---17095	28094	Melanie Peterson   2   3


--4.7 Find The Top 10 Customers Who Have Generated The Highest Number of Orders.
SELECT TOP (10) DC.customer_key , 
           DC.customer_id , 
           DC.first_name + ' ' + DC.last_name AS "Customer Name",
           COUNT(DISTINCT FS.order_number) AS "Total Orders"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_customers AS DC
ON DC.customer_key = FS.customer_key
GROUP BY DC.customer_key , DC.customer_id , DC.first_name + ' ' + DC.last_name
ORDER BY "Total Orders" DESC

--Output:
---92	11091	Dalton Perez	    28
---177	11176	Mason Roberts	    28
---186	11185	Ashley Henderson	27
---201	11200	Jason Griffin	    27
---224	11223	Hailey Patterson	27
---263	11262	Jennifer Simmons	27
---277	11276	Nancy Chapman	    27
---278	11277	Charles Jackson	    27
---288	11287	Henry Garcia	    27
---301	11300	Fernando Barnes	    27


--4.8 Find The Top 3 Customers Who Have Generated The Lowest Number of Orders.
SELECT TOP (3) DC.customer_key , 
           DC.customer_id , 
           DC.first_name + ' ' + DC.last_name AS "Customer Name",
           COUNT(DISTINCT FS.order_number) AS "Total Orders"
FROM gold.fact_sales AS FS
INNER JOIN gold.dim_customers AS DC
ON DC.customer_key = FS.customer_key
GROUP BY DC.customer_key , DC.customer_id , DC.first_name + ' ' + DC.last_name
ORDER BY "Total Orders" ASC

--Output:

---16	11015	Chloe Young	 1
---17	11016	Wyatt Hill	 1
---21	11020	Jordan King	 1